/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 */

// Code generated by go run gen.go -releaseVersion $RELEASE_VERSION -platformVersion $PLATFORM_VERSION; DO NOT EDIT.

package version

// These constants are updated by 'RELEASE_VERSION=xx.xx.xx.xx PLATFORM_VERSION=xx.xx go generate common/version'.
// It will execute 'go:generate go run gen.go' defined in release.go, which will
// update below constants based on input RELEASE_VERSION and PLATFORM_VERSION.
const (
	// ReleaseVersion is the release version when wienerchain is released.
	// It consists of 4 segments, i.e. 2.1.0.6
	ReleaseVersion = "2.1.0.6"

	// PlatformVersion is platform version when wienerchain is released.
	// It consists of 2 segments, i.e. 1.0
	PlatformVersion = "1.0"

	// GitSHA is the last commit id when wienerchain is released.
	GitSHA = notProvided
)
